config/routes.rb
Rails.application.routes.draw do
  LOCALES = /pt\-BR|es/

  scope "(:locale)", locale: LOCALES do
    devise_for :masters, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users

    require "sidekiq/web"
    if Rails.env.production?
      Sidekiq::Web.use Rack::Auth::Basic do |username, password|
        username == "mobilesenior" && password == "jan2019*"
      end
    end
    mount Sidekiq::Web, at: "/sidekiq"

    # main pages
    get 'home/educator', as: 'educator_home'
    get 'home/senior', as: 'senior_home'
    get 'home/credits', as: 'creditos'
    get 'home/info', as: 'info'
    get 'home/show_quiz_result', as: 'show_quiz_result'

    post 'message/create', as: 'message_send', to: 'messages#create'

    post '/create_group_with_users', as: 'create_group', to: 'groups#create_group_with_users'
    post '/update_users_of_group', as: 'update_group', to: 'groups#update_users_of_group'

    post '/recommend_material_to_user', as: 'recommend_material_to_user', to: 'recommendations#recommend_material_to_user'

    get '/participate', as: 'participate', to: 'home#participate'

    # question question_answers
    resources :question_answers
    resources :materials
    resources :educator_materials, controller: 'materials'
    resources :recommendations, only: [:show]
  end

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:info, :credits, :index]
  before_action :check_participation!, only: :senior

  def index
    redirect_to new_user_session_path, notice: t('controller_messages.greetings')
  end

  def educator
    @seniors = Senior.all
    @groups = current_user.groups
    @user = User.find(current_user.id)
    @materials = Material.where(user: current_user)
  end

  def senior
    clean_empty_quiz
    clean_and_set_session_questions

    @q_id = session[:questions_to_answer].sample

    @quiz_list = Quiz.where(user: current_user)
    @user = User.find(current_user.id)
    @recommendations = Recommendation.where(user: current_user)

    participations = current_user.mobile_participations

    if participations.count == 0
      @participate = false
    else
      @participate = true
    end
  end

  def credits
  end

  def info
    @message = Message.new
  end

  def show_quiz_result
    sleep 3
    @quiz = Quiz.find(params[:quiz_id])
  end

  def participate
    participate = params[:participate]
    user = User.find(params[:user_id])
    participation = MobileParticipation.create(user: user, participate: participate)

    if participation.participate
      new_q_id = session[:questions_to_answer].sample
      redirect_to new_question_answer_path(init_quiz: true, q_id: new_q_id), notice: t('controller_messages.participation_answer_q')
    else
      sign_out(current_user)
      redirect_to new_user_session_path, notice: t('controller_messages.participation_answer')
    end
  end

  private
  def clean_empty_quiz
    user_quiz = Quiz.where(user: current_user)

    user_quiz.each do |quiz|
      quiz_answers = quiz.question_answers

      if quiz_answers.count == 0
        quiz.destroy
      end
    end
  end

  def clean_and_set_session_questions
    session[:questions_to_answer] = []
    session[:answered_questions] = []

    number_of_questions = Question.all.count
    session[:questions_to_answer] = (1..number_of_questions).to_a
  end

  def check_participation!
    participations = current_user.mobile_participations

    if participations.count > 0
      participate = participations.last.participate

      if !participate
        sign_out(current_user)
        redirect_to new_user_session_path, notice: t('controller_messages.disabled_user')
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def first_name(name)
    name.split.first
  end

  def age(birthday)
    age = Date.today.year - birthday.year
    age -= 1 if Date.today < birthday + age.years

    age
  end

  def boolean_to_s(value)
    if value
      t('senior_notification.answer_yes')
    else
      t('senior_notification.answer_no')
    end
  end

  def skill_groups_results(quiz)
    results = []
    quiz.skill_groups.each do |skill_group|
      results.push({
        id: skill_group.id,
        title: skill_group.title,
        value: quiz.skill_group_result(skill_group) ? skill_level(quiz.skill_group_result(skill_group).value) : nil
        })
    end

    results
  end

  def skills_results(quiz, skill_id)
    results = []

    skills = quiz.skills.select { |skill| skill.skill_group.id == skill_id}

    skills.each do |skill|
      results.push({
        id: skill.id,
        title: skill.title,
        value: quiz.skill_result(skill) ? skill_level(quiz.skill_result(skill).value) : nil
        })
    end

    results
  end

  def last_answered_question(quiz = nil)
    last_question_answered = '-'

    begin
      last_question_answered = quiz.question_answers.last.question.id
    rescue StandardError
      last_question_answered = '-'
    end

    return last_question_answered
  end
end

app/views/home/credits.html.erb
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="display-4 font-weight-bold" style="word-break: break-all;"><%=t('credits.acknowledgments')%></h1>
            <br/>
            <p style="font-size: 18px;"><%=t('credits.line1')%></p>
            <p style="font-size: 18px;"><%=t('credits.line2')%></p>
            <p style="font-size: 18px;"><%=t('credits.line3')%></p>
            <p style="font-size: 18px;"><%=t('credits.line4')%></p>
            <p style="font-size: 18px;"><%=t('credits.line5')%></p>
            <p style="font-size: 18px;"><%=t('credits.line6')%></p>
            <p style="font-size: 18px;"><%=t('credits.line7')%></p>
            <p style="font-size: 18px;"><%=t('credits.line8')%></p>
        </div>
    </div>
</div>
<div class="row ">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
        <div class="card border-primary mb-3 mw-100 shadow" style="max-width: 20rem;">
            <div class="card-header" style="font-size: 24px; font-weight: bold;"><%=t('credits.coordenation')%></div>
            <div class="card-body">
                <h4 class="card-title">Dra Leticia Rocha Machado</h4>
                <p class="card-text"><p style="font-size: 18px;"><%=t('credits.qualifications')%></p><p style="font-size: 18px;"><%=t('credits.email')%>: <a href="mailto:leticiarmachado@gmail.com">leticiarmachado@gmail.com</a></p><%=t('credits.curriculum')%>: <a href="http://lattes.cnpq.br/7669562366317063" style="font-size: 18px;">lattes.cnpq.br/7669562366317063</a></p>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
        <div class="card border-primary mb-3 mw-100 shadow" style="max-width: 20rem;">
            <div class="card-header" style="font-size: 24px; font-weight: bold;"><%=t('credits.team')%></div>
            <div class="card-body">
                <h4 class="card-title"><%=t('credits.images')%></h4>
                <p class="card-text" style="font-size: 18px;">Mariana Marques</p>
                <h4 class="card-title"><%=t('credits.design')%></h4>
                <p class="card-text" style="font-size: 18px;">Anderson Bier Saldanha</p>
                <h4 class="card-title"><%=t('credits.development')%></h4>
                <p class="card-text" style="font-size: 18px;">Magnun Furtado</p>
            </div>
        </div>
    </div>
</div>

app/views/home/senior.html.erb
<% if !@participate %>
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="display-3"><b><%=t('senior_notification.greetings')%></b></h1>
            <p class="lead"><%=t('senior_notification.line_1')%></p>
            <p class="lead"><%=t('senior_notification.line_2')%></p>
            <p class="lead"><%=t('senior_notification.line_3')%></p><br/>
            <p class="lead"><%=t('senior_notification.question')%></p><br/>
            <%= link_to(t('senior_notification.answer_yes'), participate_path(user_id: current_user.id, participate: true), class: "btn btn-primary btn-lg", role: "button") %>
            <%= link_to(t('senior_notification.answer_no'), participate_path(user_id: current_user.id, participate: false), class: "btn btn-outline-danger btn-lg", role: "button") %>
        </div>
    </div>
</div>
<% end %>

<div class="row ">
    <div class="col-xl-4 col-lg-4 col-12 col-sm-12 col-md-4 order-xl-1 order-lg-1 order-md-1 order-sm-2 order-2">
        <div class="card mb-3 mw-100 bg-primary text-white shadow" style="max-width: 20rem;">
            <div class="card-header">
                <%= link_to(fa_icon("edit", text: t('buttons.edit')), edit_user_registration_path(current_user, locale: I18n.locale), class: "btn btn-light float-right")%>
                <b><%=t('general_infos.my_profile')%></b>
            </div>
            <div class="card-body">
                <h4 class="card-title"><%=t('activerecord.attributes.user.name')%></h4>
                <p class="card-text"><%= current_user.name %></p>
                <h4 class="card-title"><%=t('general_infos.age')%></h4>
                <p class="card-text"><%= age(current_user.birthday) %></p>
                <h4 class="card-title"><%=t('activerecord.attributes.user.email')%></h4>
                <p class="card-text"><%= current_user.email %></p>
            </div>
        </div>
        <div class="card mb-3 mw-100 text-white bg-success shadow" style="max-width: 20rem;">
            <div class="card-header">
              <%=t('general_infos.rec_and_mat')%>
            </div>
            <div class="card-body">
                <div class="list-group">
                  <% @recommendations.each do |recommendation| %>
                    <div class="list-group-item list-group-item-success">
                        <p><%= format_default_recommendation_title(recommendation.title) %></p>
                        <%= link_to fa_icon("eye", text: t('buttons.view')), recommendation_path(recommendation), class: "btn btn-light" %>
                    </div>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-12 col-xl-8 col-lg-8 col-md-8 order-xl-2 order-lg-2 order-md-2 order-sm-1 order-1">
        <div class="card mb-3 mw-100 bg-warning text-white shadow" style="max-width: 20rem;">
            <div class="card-header">
              <%= link_to(fa_icon("check", text: t('buttons.redo')), new_question_answer_path(init_quiz: true, q_id: @q_id), class: "btn btn-light float-right") %>
                <b><%=t('general_infos.quiz_results_title')%></b>
            </div>
            <div class="card-body bg-warning">
                <div id="panels1" role="tablist">
                    <% @quiz_list.order('created_at DESC').each do |quiz| %>
                      <div class="card list-group-item-warning">
                          <div class="card-header" role="tab">
                              <h5 class="mb-0">
                                <a data-toggle="collapse" href="#collapse<%= quiz.id %>" aria-expanded="true" aria-controls="collapse<%= quiz.id %>" class="list-group-item-warning">
                                  <%=t('general_infos.made_in')%> <%=I18n.l quiz.created_at, format: :long %></a> </h5>
                          </div>
                          <div id="collapse<%= quiz.id %>" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#panels1">
                              <div class="card-body">
                                <h3><%=t('general_infos.quiz_results')%></h3>
                                <p><%=t('general_infos.done')%>: <%= boolean_to_s(quiz.complete) %> </p>

                                <% if quiz.complete %>
                                  <% skill_groups_results(quiz).each do |skg_result| %>
                                    <h4><%=t('general_infos.skill_group')%>: <%= I18n.locale == :es ? translate_to_es_skill_group(skg_result[:title]) : skg_result[:title] %></h4>
                                    <p><%=t('general_infos.level')%>: <%= I18n.locale == :es ? translate_to_es_level(skg_result[:value]) : skg_result[:value] %></p>

                                    <ul>
                                      <% skills_results(quiz, skg_result[:id]).each do |sk_result| %>
                                        <li>
                                          <h5><%=t('general_infos.skill')%>: <%= I18n.locale == :es ? translate_to_es_skill(sk_result[:title]) : sk_result[:title] %></h5>
                                          <p><%=t('general_infos.level')%>: <%= I18n.locale == :es ? translate_to_es_level(sk_result[:value]) : sk_result[:value] %></p>
                                        </li>
                                      <% end %>
                                    </ul>
                                  <% end %>
                                <% else %>
                                  <p><%=t('general_infos.last_question')%>: <%= last_answered_question(quiz) %></p>
                                <% end %>
                              </div>
                          </div>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/show_quiz_result.html.erb
<!-- # Loading -->
<script>
    $(document).ready(function() {
        $('#overlay').fadeOut(4000,function(){
            $('#container').fadeIn(1500);
        });
    });
</script>

<div id="overlay" class="loading-screen">
    <p><%=t('quiz_end_page.loading_recommendations')%></p>
</div>
<div id="container" class="row" style="display:none;">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="display-5"><%=t('quiz_end_page.quiz_end')%></h1>
            <hr />

            <p class="lead"><%=t('quiz_end_page.text_1')%></p>
            <p class="lead"><%=t('quiz_end_page.text_2')%></p>

    <div class="col-12 col-sm-12 col-xl-8 col-lg-8 col-md-8 order-xl-2 order-lg-2 order-md-2 order-sm-1 order-1">
        <div class="card mb-3 mw-100 bg-warning text-white shadow" style="max-width: 20rem;">
            <div class="card-header">
                <b><%=t('quiz_end_page.recommendations')%></b>
            </div>
            <div class="card-body bg-warning">
                <div id="panels1" role="tablist">
                    <% @quiz.recommendations.each do |recommendation| %>
                      <div class="card list-group-item-warning">
                          <div class="card-header" role="tab">
                              <h5 class="mb-0">
                                <a data-toggle="collapse" href="#collapse<%= recommendation.id %>" aria-expanded="true" aria-controls="collapse<%= recommendation.id %>" class="list-group-item-warning">
                                  <%=format_default_recommendation_title(recommendation.title) %>
                                </a> </h5>
                          </div>
                          <div id="collapse<%= recommendation.id %>" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#panels1">
                              <div class="card-body">
                              <p class="lead"><b><%= I18n.locale == :es ? translate_to_es_recommendation_content(recommendation.content) : recommendation.content %></b></p>
                                <h3><%=t('quiz_end_page.materials')%>:</h3>
                                <% recommendation.materials.each do |material| %>
                                  <ul>
                                    <li>
                                      <div>
                                        <p class="lead"><b><%= format_material_view(I18n.locale, material) %></b></p>
                                        <p class="lead"> <%= link_to fa_icon("eye", text: t('buttons.view_mat')), material_path(material) %></p>
                                      </div>
                                    </li>
                                  </ul>
                                <% end %>
                              </div>
                          </div>
                      </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
            <%= link_to fa_icon("home", text: t('buttons.back_to_home')), senior_home_path, class: "btn btn-primary btn-lg" %>
        </div>
    </div>
</div>