config/routes.rb
Rails.application.routes.draw do
  LOCALES = /pt\-BR|es/

  scope "(:locale)", locale: LOCALES do
    devise_for :masters, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    devise_for :users

    require "sidekiq/web"
    if Rails.env.production?
      Sidekiq::Web.use Rack::Auth::Basic do |username, password|
        username == "mobilesenior" && password == "jan2019*"
      end
    end
    mount Sidekiq::Web, at: "/sidekiq"

    # main pages
    get 'home/educator', as: 'educator_home'
    get 'home/senior', as: 'senior_home'
    get 'home/credits', as: 'creditos'
    get 'home/info', as: 'info'
    get 'home/show_quiz_result', as: 'show_quiz_result'

    post 'message/create', as: 'message_send', to: 'messages#create'

    post '/create_group_with_users', as: 'create_group', to: 'groups#create_group_with_users'
    post '/update_users_of_group', as: 'update_group', to: 'groups#update_users_of_group'

    post '/recommend_material_to_user', as: 'recommend_material_to_user', to: 'recommendations#recommend_material_to_user'

    get '/participate', as: 'participate', to: 'home#participate'

    # question question_answers
    resources :question_answers
    resources :materials
    resources :educator_materials, controller: 'materials'
    resources :recommendations, only: [:show]
  end

  root to: 'home#index'
end

app/models/default_material.rb
class DefaultMaterial < Material
end

app/models/educator.rb
class Educator < User
  validates_presence_of :educational_institution
end

app/models/educator_material.rb
class EducatorMaterial < Material
end

app/models/generic_answer.rb
class GenericAnswer < ApplicationRecord
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :user

  belongs_to :user
  has_many :group_participations

  def users
    return GroupParticipation.where(group: self).map { |x| User.find(x.user.id) }
  end
end

app/models/master.rb
class Master < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/material.rb
class Material < ApplicationRecord
  validates_presence_of :user

  belongs_to :user

  has_many :material_recommendations
  has_many :recommendations, through: :material_recommendations

  scope :default_material, -> { where(type: 'DefaultMaterial') }
  scope :educator_material, -> { where(type: 'EducatorMaterial') }

  def self.types
    %w(DefaultMaterial EducatorMaterial)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :name, :email, :content
end

app/models/question.rb
class Question < ApplicationRecord
  validates_presence_of :user, :skill

  belongs_to :user
  belongs_to :skill

  has_many :question_answers
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord
  validates_presence_of :question, :user, :answer

  belongs_to :question
  belongs_to :user
  belongs_to :quiz

  def question_statement
    return Question.find(self.question_id).statement
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  has_many :question_answers
  has_many :recommendations

  def skill_groups
    self.question_answers.map{ |question_answer|
      question_answer.question.skill.skill_group }.uniq
  end

  def skills
    self.question_answers.map{ |question_answer|
      question_answer.question.skill }.uniq
  end

  def skill_group_result(skill_group)
    SkillGroupResult.where(quiz: self, skill_group: skill_group).first
  end

  def skill_result(skill)
    SkillResult.where(quiz: self, skill: skill).first
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  validates_presence_of :user

  belongs_to :user
  belongs_to :quiz

  has_many :material_recommendations
  has_many :materials, through: :material_recommendations
end

app/models/senior.rb
class Senior < User
  def groups
    return GroupParticipation.where(user: self).map { |x| Group.find(x.group.id) }
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates_presence_of :skill_group

  has_many :questions

  belongs_to :skill_group
end

app/models/skill_group.rb
class SkillGroup < ApplicationRecord
  has_many :skills
end

app/models/skill_result.rb
class SkillResult < ApplicationRecord
  validates_presence_of :skill, :quiz

  belongs_to :skill
  belongs_to :quiz
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :type, :name, :birthday, :gender, :phone, :country,
                        :state, :city, :education

  scope :educator, -> { where(type: 'Educator') }
  scope :senior, -> { where(type: 'Senior') }

  # to Educator
  has_many :groups
  has_many :questions

  # to Senior
  has_many :group_participations
  has_many :question_answers
  has_many :recommendations
  has_many :quizzes

  has_many :mobile_participations
  has_many :generic_answers

  def self.types
    %w(Educator Senior)
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  before_action :set_material, only: [:show, :edit, :update, :destroy]

  def index
    @materials = Material.where(user: current_user).order('updated_at desc')
  end

  def show
  end

  def new
    @material = Material.new
  end

  def edit
  end

  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to materials_url, notice: t('controller_messages.material_created')
    else
      render :new
    end
  end

  def update
    if @material.update(material_params)
      redirect_to materials_url, notice: t('controller_messages.material_updated')
    else
      render :edit
    end
  end

  def destroy
    @material.destroy

    redirect_to materials_url, notice: t('controller_messages.material_deleted')
  end

  private
    def set_material
      @material = Material.find(params[:id])
    end

    def material_type
      if @material
        return @material.type
      else
        return ''
      end
    end

    def material_params
      params.require(
        params[:type] == "EducatorMaterial" || material_type == "EducatorMaterial" ?
        :educator_material : :material
      ).permit(:title, :content, :description, :type, :user_id, :language, :alt_lang_title, :alt_lang_description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def first_name(name)
    name.split.first
  end

  def age(birthday)
    age = Date.today.year - birthday.year
    age -= 1 if Date.today < birthday + age.years

    age
  end

  def boolean_to_s(value)
    if value
      t('senior_notification.answer_yes')
    else
      t('senior_notification.answer_no')
    end
  end

  def skill_groups_results(quiz)
    results = []
    quiz.skill_groups.each do |skill_group|
      results.push({
        id: skill_group.id,
        title: skill_group.title,
        value: quiz.skill_group_result(skill_group) ? skill_level(quiz.skill_group_result(skill_group).value) : nil
        })
    end

    results
  end

  def skills_results(quiz, skill_id)
    results = []

    skills = quiz.skills.select { |skill| skill.skill_group.id == skill_id}

    skills.each do |skill|
      results.push({
        id: skill.id,
        title: skill.title,
        value: quiz.skill_result(skill) ? skill_level(quiz.skill_result(skill).value) : nil
        })
    end

    results
  end

  def last_answered_question(quiz = nil)
    last_question_answered = '-'

    begin
      last_question_answered = quiz.question_answers.last.question.id
    rescue StandardError
      last_question_answered = '-'
    end

    return last_question_answered
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/materials/_form.html.erb
<%= form_for(material) do |f| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> proibiram de salvar esse material:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id, hidden: true %>
    <%= f.text_field :user_id, value: current_user.id, hidden: true %>
  </div>

  <div class="field">
    <%= f.label :type, hidden: true %>
    <%= f.text_field :type, value: "EducatorMaterial", hidden: true %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :alt_lang_title %>
    <%= f.text_field :alt_lang_title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.select :language, ['pt', 'es']%>
  </div>

  <div class="actions">
    <%= f.submit t('buttons.save') %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="ui horizontal divider header">
              <%=t('general_infos.edit_material')%>
            </h1>

            <%= render 'form', material: @material %>

            <br/>
            <%= link_to t('buttons.my_materials'), materials_path %>
        </div>
    </div>
</div>

app/views/materials/index.html.erb
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="display-3"><%=t('buttons.my_materials')%></h1>

            <div class="row" id="new-material-button">
                <div class="new-btn">
                    <%= link_to t('buttons.new_mat'), new_material_path, type:"button", class:"btn btn-primary" %>
                    <%= link_to t('buttons.back'), educator_home_path, type:"button", class:"btn btn-outline-danger" %>
                </div>
            </div>

            <div class="row">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col"><%=t('modal_pages.title')%></th>
                    <th scope="col"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @materials.each do |material| %>
                    <tr>
                      <td><%= format_material_view(I18n.locale, material) %></td>
                      <td>
                      <%= link_to fa_icon("eye"), material_path(material)%>
                      </td>
                      <% if material.type != 'DefaultMaterial' %>
                      <td><%= link_to fa_icon("edit"), edit_material_path(material) %></td>
                      <td><%= link_to fa_icon("trash"), material_path(material),
                            style: "color: red;",
                            method: :delete,
                            data: { confirm: t('modal_pages.confirmation_question') } %></td>
                      <% else %>
                      <td>-</td>
                      <td>-</td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

app/views/materials/new.html.erb
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="ui horizontal divider header">
              <%=t('general_infos.create_material')%>
            </h1>

            <%= render 'form', material: @material %>

            <br/>
            <%= link_to t('buttons.my_materials'), materials_path %>
        </div>
    </div>
</div>

app/views/materials/show.html.erb
<div class="row">
    <div class="col-xl-10 offset-xl-1">
        <div class="jumbotron" style="background-color: rgba(255, 255, 255, 0.7);">
            <h1 class="display-3"><%=t('buttons.view_mat')%></h1>

            <p class="lead"><b><%= format_material_view(I18n.locale, @material) %></b></p>
            <p><b><%=t('material_page.language')%>:</b> <%= format_language(@material.language) %></p>

            <% material_type = material_type(@material.content) %>

            <% if material_type == 'youtube-video' %>
                <% video_id = youtube_video_id(@material.content) %>

                <iframe id="ytplayer" type="text/html" class='video-box'
                    src="https://www.youtube.com/embed/<%=video_id%>?autoplay=1&origin=localhost:3000"
                    frameborder="0">
                </iframe>

                <p class="lead"> <%= link_to fa_icon("external-link", text: t('general_infos.go_to_youtube')), @material.content, target: :_blank %></p>
            <% else %>
                <p class="lead"> <%= link_to fa_icon("external-link", text: t('general_infos.go_to_mat')), @material.content, target: :_blank %></p>
            <% end %>

            <% if current_user.type == "Educator"%>
                <div>
                    <h5><%=t('material_page.mat_data')%></h5>
                    <p><b><%=t('material_page.languages')%>:</b> <%= format_language(@material.language) %></p>
                    <p><b><%=t('material_page.created_at')%>: </b> <%= I18n.l @material.created_at, format: :long %></p>
                    <p><b><%=t('material_page.updated_at')%>:</b> <%= I18n.l @material.updated_at, format: :long %></p>
                </div>
                <br/>
                <%= link_to fa_icon("book", text: t('buttons.my_materials')), materials_path %>
            <% else %>
                <%= link_to fa_icon("home", text: t('buttons.back_to_home')), senior_home_path %>
            <% end %>
        </div>
    </div>
</div>